# Generated by Django 6.0.2 on 2026-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
