# Generated by Django 6.0.2 on 2026-02-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_delete_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='teamMember',
        ),
    ]
