# Generated by Django 6.0.2 on 2026-02-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_rename_teammemberentity_to_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('education', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='team.teammember')),
            ],
            options={
                'db_table': 'team_resume',
            },
        ),
    ]
