# Generated by Django 6.0.2 on 2026-02-28 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='team.teammember')),
            ],
            options={
                'db_table': 'team_contact',
            },
        ),
    ]
