# Generated by Django 6.0.2 on 2026-03-01 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_remove_contact_type_remove_contact_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
