# Generated by Django 6.0.2 on 2026-03-02 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_resume_date_created_resume_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='home_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Use numbers only.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Use numbers only.', regex='^\\d+$')]),
        ),
    ]
