# Generated by Django 6.0.2 on 2026-03-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_member_photos/'),
        ),
    ]
